#ifndef LPS221HB_H
#define LPS221HB_H

#include "defines.h"
#include "i2c_controller.h"

//????? ??????????
#define LPS22HB_ADDR			0xBA

//??? ?????? ??????

//???????? ??????????????? ??????????
#define LPS22HB_WHO_AM_I		0xB1
/********************?????? ????????? ??????????********************/

#define LPS22HB_REG_INTERRUPT_CFG	0x0B
#define LPS22HB_REG_THS_P_L			0x0C
#define LPS22HB_REG_THS_P_H			0x0D
#define LPS22HB_REG_WHO_AM_I		0x0F
#define LPS22HB_REG_CTRL_REG1		0x10
#define LPS22HB_REG_CTRL_REG2		0x11
#define LPS22HB_REG_CTRL_REG3		0x12
#define LPS22HB_REG_FIFO_CTRL		0x14
#define LPS22HB_REG_REF_P_XL		0x15
#define LPS22HB_REG_REF_P_L			0x16
#define LPS22HB_REG_REF_P_H			0x17
#define LPS22HB_REG_RPDS_L			0x18
#define LPS22HB_REG_RPDS_H			0x19
#define LPS22HB_REG_RES_CONF		0x1A
#define LPS22HB_REG_INT_SOURCE		0x25
#define LPS22HB_REG_FIFO_STATUS		0x26
#define LPS22HB_REG_STATUS			0x27
#define LPS22HB_REG_PRESS_OUT_XL	0x28
#define LPS22HB_REG_PRESS_OUT_L		0x29
#define LPS22HB_REG_PRESS_OUT_H		0x2A
#define LPS22HB_REG_TEMP_OUT_L		0x2B
#define LPS22HB_REG_TEMP_OUT_H		0x2C
#define LPS22HB_REG_LPFP_RES		0x33

/*******************************************************************/

/********************???? ?????????********************/

//??????? INTERRUPT_CFG
#define __LPS22HB_INTERRUPT_CFG_PHE						0
#define __LPS22HB_INTERRUPT_CFG_PLE						1
#define __LPS22HB_INTERRUPT_CFG_LIR						2
#define __LPS22HB_INTERRUPT_CFG_DIFF_EN					3
#define __LPS22HB_INTERRUPT_CFG_RESET_AZ				4
#define __LPS22HB_INTERRUPT_CFG_AUTOZERO				5
#define __LPS22HB_INTERRUPT_CFG_RESET_ARP				6
#define __LPS22HB_INTERRUPT_CFG_AUTORIFP				7
#define _LPS22HB_INTERRUPT_CFG_AUTORIFP_EN				(1 << __LPS22HB_INTERRUPT_CFG_AUTORIFP)
#define _LPS22HB_INTERRUPT_CFG_AUTORIFP_DIS				(0 << __LPS22HB_INTERRUPT_CFG_AUTORIFP)
#define _LPS22HB_INTERRUPT_CFG_AUTORIFP_RESET			(1 << __LPS22HB_INTERRUPT_CFG_RESET_ARP)
#define _LPS22HB_INTERRUPT_CFG_AUTOZERO_EN				(1 << __LPS22HB_INTERRUPT_CFG_AUTOZERO)
#define _LPS22HB_INTERRUPT_CFG_AUTOZERO_DIS				(0 << __LPS22HB_INTERRUPT_CFG_AUTOZERO)
#define _LPS22HB_INTERRUPT_CFG_AUTOZERO_RESET			(1 << __LPS22HB_INTERRUPT_CFG_RESET_AZ)
#define _LPS22HB_INTERRUPT_CFG_INT_GENERATION_EN		(1 << __LPS22HB_INTERRUPT_CFG_DIFF_EN)
#define _LPS22HB_INTERRUPT_CFG_INT_GENERATION_DIS		(0 << __LPS22HB_INTERRUPT_CFG_DIFF_EN)
#define _LPS22HB_INTERRUPT_CFG_INT_LATCHED_EN			(1 << __LPS22HB_INTERRUPT_CFG_LIR)
#define _LPS22HB_INTERRUPT_CFG_INT_LATCHED_DIS			(0 << __LPS22HB_INTERRUPT_CFG_LIR)
#define _LPS22HB_INTERRUPT_CFG_INT_PRESS_LOW_EVENT_EN	(1 << __LPS22HB_INTERRUPT_CFG_PLE)
#define _LPS22HB_INTERRUPT_CFG_INT_PRESS_LOW_EVENT_DIS	(0 << __LPS22HB_INTERRUPT_CFG_PLE)
#define _LPS22HB_INTERRUPT_CFG_INT_PRESS_HIGH_EVENT_EN	(1 << __LPS22HB_INTERRUPT_CFG_PHE)
#define _LPS22HB_INTERRUPT_CFG_INT_PRESS_HIGH_EVENT_DIS	(1 << __LPS22HB_INTERRUPT_CFG_PHE)

//??????? CTRL_REG1
#define __LPS22HB_CTRL_REG1_SIM			0
#define __LPS22HB_CTRL_REG1_BDU			1
#define __LPS22HB_CTRL_REG1_LPFP_CFG	2
#define __LPS22HB_CTRL_REG1_EN_LPFP		3
#define __LPS22HB_CTRL_REG1_ODR0		4
#define __LPS22HB_CTRL_REG1_ODR1		5
#define __LPS22HB_CTRL_REG1_ODR2		6
#define _LPS22HB_CTRL_REG1_ODR_ONE		0x00
#define _LPS22HB_CTRL_REG1_ODR_1Hz		(1 << __LPS22HB_CTRL_REG1_ODR0)
#define _LPS22HB_CTRL_REG1_ODR_10Hz		(1 << __LPS22HB_CTRL_REG1_ODR1)
#define _LPS22HB_CTRL_REG1_ODR_25Hz		(1 << __LPS22HB_CTRL_REG1_ODR0) | (1 << __LPS22HB_CTRL_REG1_ODR1)
#define _LPS22HB_CTRL_REG1_ODR_50Hz		(1 << __LPS22HB_CTRL_REG1_ODR2)
#define _LPS22HB_CTRL_REG1_ODR_75Hz		(1 << __LPS22HB_CTRL_REG1_ODR0) | (1 << __LPS22HB_CTRL_REG1_ODR2)
#define _LPS22HB_CTRL_REG1_BDU_EN		(1 << __LPS22HB_CTRL_REG1_BDU)
#define _LPS22HB_CTRL_REG1_BDU_DIS		(0 << __LPS22HB_CTRL_REG1_BDU)
#define _LPS22HB_CTRL_REG1_LPFP_EN		(1 << __LPS22HB_CTRL_REG1_EN_LPFP)
#define _LPS22HB_CTRL_REG1_LPFP_DIS		(0 << __LPS22HB_CTRL_REG1_EN_LPFP)
#define _LPS22HB_CTRL_REG1_LPFP_EN		(1 << __LPS22HB_CTRL_REG1_EN_LPFP)


//??????? CTRL_REG2
#define __LPS22HB_CTRL_REG2_ONE_SHOT			0
#define __LPS22HB_CTRL_REG2_SWRESET				2
#define __LPS22HB_CTRL_REG2_I2C_DIS				3
#define __LPS22HB_CTRL_REG2_IF_ADD_INC			4
#define __LPS22HB_CTRL_REG2_STOP_ON_FTH			5
#define __LPS22HB_CTRL_REG2_FIFO_EN				6
#define __LPS22HB_CTRL_REG2_BOOT				7
#define _LPS22HB_CTRL_REG2_FIFO_EN				(1 << __LPS22HB_CTRL_REG2_FIFO_EN)
#define _LPS22HB_CTRL_REG2_FIFO_DIS				(0 << __LPS22HB_CTRL_REG2_FIFO_EN)
#define _LPS22HB_CTRL_REG2_FIFO_WATERMARK_EN	(1 << __LPS22HB_CTRL_REG2_STOP_ON_FTH)
#define _LPS22HB_CTRL_REG2_FIFO_WATERMARK_DIS	(0 << __LPS22HB_CTRL_REG2_STOP_ON_FTH)
#define _LPS22HB_CTRL_REG2_SWRESET				(1 << __LPS22HB_CTRL_REG2_SWRESET)
#define _LS22HB_CTRL_REG2_ONE_SHOT_ACQUIRED		(1 << __LPS22HB_CTRL_REG2_ONE_SHOT)
#define _LS22HB_CTRL_REG2_ADD_INC_EN			(1 << __LPS22HB_CTRL_REG2_IF_ADD_INC)
#define _LS22HB_CTRL_REG2_ADD_INC_DIS			(0 << __LPS22HB_CTRL_REG2_IF_ADD_INC)

//??????? FIFO_CTRL
#define __LPS22HB_FIFO_CTRL_F_MODE0		5
#define __LPS22HB_FIFO_CTRL_F_MODE1		6
#define __LPS22HB_FIFO_CTRL_F_MODE2		7
#define _LPS22HB_FIFO_CTRL_MODE_BYPASS	0x00

//??????? STATUS
#define __LPS22HB_STATUS_P_DA	0
#define __LPS22HB_STATUS_T_DA	1
#define __LPS22HB_STATUS_P_OR	4
#define __LPS22HB_STATUS_T_OR	5

struct LpsFlags
{
	bool inited:1;
	bool setupped:1;
	bool heating:1;
};

class LPS22HB
{
	public:
		void Init(I2CController*);
		void Process();
		void GetStatus(struct LpsFlags* flags);
		double temp, pressure;
	
	private:
		void CheckDevice();
		void SetupDevice();
		void CountPressure();
		void CountTemp();
	
		LpsFlags flags;
		I2CController* i2c;
};

#endif
